---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: build-app
spec:
  inputs:
    params:
      - name: app
        type: string

    ### resource: are artifacts ###
    resources:
      - name: src    ### has a name
        type: git    ### has a type (built into Tekton)

  outputs:
    ### resources can be both input & output
    resources:
      - name: img
        type: image

  steps:
    - name: step-00
      image: busybox
      script: |
        #!/bin/sh
        set +x

        echo Building app   $(inputs.params.app)
        echo Going to clone $(inputs.resources.src.url)
        echo Outputimg      $(outputs.resources.img.url)
