---
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: build-app-0401
spec:
  taskRef:
    name: build-app

  inputs:
    params:
      - name: app
        value: voting-api

    resources:
      - name: src
        resourceRef:
          name: api-repo

  outputs:
    resources:
      - name: img   ### must be the name of the resource in task
        resourceRef:
          name: api-image
