---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: greetings-task
spec:
  ### Inputs ###
  inputs:
    params:
      - name: greetings
        type: string  ### | array
        default: hello
        description: what is your greeting message
  ###  ------------ ###
  steps:
    - name: step-1
      image: busybox
      command:
        - echo
      args:
        - $(inputs.params.greetings), world
          # ^^^^^^^^^^^^^^^^^^^^^^^^^^^

    - name: step-2-run-a-script
      image: busybox
      script: |
        #!/bin/sh
        set +x
        echo "$(inputs.params.greetings), I am at $(pwd)"
        #       ^^^^^^^^^^^^^^^^^^^^^^
