---
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: greetings-taskrun-0302
spec:
  taskRef:
    name: greetings-task
  ### Set parameters ###
  inputs:
    params:
      - name: greetings   ### <<< name of the param
        value: hola, 你好 , bonjour, नमस्ते
