---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: api-repo
spec:
  type: git
  params:
    - {name: url, value: http://github.com/sthaha/vote-api.git}
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: api-image
spec:
  type: image
  params:
    - {name: url, value: image-registry.openshift-image-registry.svc:5000/sthaha-triggers/api:latest}
