apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: build-and-deploy-api
spec:
  pipelineRef:
    name: build-and-deploy-api
  resources:
    - name: api-repo
      resourceRef:
        name: api-repo
    - name: api-image
      resourceRef:
        name: api-image
